name: Run Scraper

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up Database URL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}  # Use GitHub Secrets for security
          FLASK_SECRET: ${{ secrets.FLASK_SECRET }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
          SMTP_ADDRESS: ${{ secrets.SMTP_ADDRESS }}

      - name: Run Scraper
        run: |
          python scraper.py
